/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sun.security.rsa.RSACore;

/**
 *
 * @author Hugo
 */
public class CrearTarea extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmpleado
     */
    public CrearTarea() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());

        Connection cn = conexion.Conexion.conectar();
        try {

            PreparedStatement ps = cn.prepareStatement("SELECT Nombre, Apellidos FROM usuarios WHERE Tipo = ?");
            ps.setString(1, "Empleado");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                ComboBoxEmpleadoAsignado.addItem(rs.getString(1) + " " + rs.getString(2));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelFondo = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CampoNotas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BotonCrearTarea = new javax.swing.JButton();
        BotonURL = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CampoFecEntrega = new javax.swing.JTextField();
        ComboBoxEmpleadoAsignado = new javax.swing.JComboBox<>();
        LabelVolver = new javax.swing.JLabel();
        BotonAgregarEmpleado = new javax.swing.JButton();
        ComboBoxPrioridad = new javax.swing.JComboBox<>();
        ComboBoxEstado = new javax.swing.JComboBox<>();
        CampoEmpleados = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("PlanifiKa");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Notas:");
        PanelFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, -1, -1));

        CampoNotas.setBackground(java.awt.Color.black);
        CampoNotas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNotas.setForeground(java.awt.Color.white);
        PanelFondo.add(CampoNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 270, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Estado:");
        PanelFondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Prioridad:");
        PanelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        CampoNombre.setBackground(java.awt.Color.black);
        CampoNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNombre.setForeground(java.awt.Color.white);
        PanelFondo.add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 270, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Nombre:");
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("URL archivo adjunto:");
        PanelFondo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Empleados disponibles:");
        PanelFondo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, -1, -1));

        BotonCrearTarea.setBackground(java.awt.Color.black);
        BotonCrearTarea.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonCrearTarea.setForeground(java.awt.Color.white);
        BotonCrearTarea.setText("Crear tarea");
        BotonCrearTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearTareaActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonCrearTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 530, 240, 60));

        BotonURL.setBackground(java.awt.Color.black);
        BotonURL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonURL.setForeground(java.awt.Color.white);
        BotonURL.setText("Añadir foto");
        BotonURL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonURLActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 260, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Fecha de entrega:");
        PanelFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        CampoFecEntrega.setBackground(java.awt.Color.black);
        CampoFecEntrega.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoFecEntrega.setForeground(java.awt.Color.white);
        PanelFondo.add(CampoFecEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 250, -1));

        ComboBoxEmpleadoAsignado.setBackground(java.awt.Color.black);
        ComboBoxEmpleadoAsignado.setForeground(java.awt.Color.white);
        PanelFondo.add(ComboBoxEmpleadoAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 350, 270, 40));

        LabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volveratras.png"))); // NOI18N
        LabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolverMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 70, 70));

        BotonAgregarEmpleado.setBackground(java.awt.Color.black);
        BotonAgregarEmpleado.setForeground(java.awt.Color.white);
        BotonAgregarEmpleado.setText("Agregar empleado");
        BotonAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarEmpleadoActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, -1, -1));

        ComboBoxPrioridad.setBackground(java.awt.Color.black);
        ComboBoxPrioridad.setForeground(java.awt.Color.white);
        ComboBoxPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));
        PanelFondo.add(ComboBoxPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 250, 40));

        ComboBoxEstado.setBackground(java.awt.Color.black);
        ComboBoxEstado.setForeground(java.awt.Color.white);
        ComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retrasada", "Pendiente", "Finalizada" }));
        PanelFondo.add(ComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 250, 40));

        CampoEmpleados.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CampoEmpleados.setForeground(java.awt.Color.white);
        CampoEmpleados.setText("0");
        PanelFondo.add(CampoEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 430, 30, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Empleados añadidos: ");
        PanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, -1, 20));

        labelFondo.setBackground(java.awt.Color.black);
        labelFondo.setForeground(java.awt.Color.white);
        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondotfg.png"))); // NOI18N
        PanelFondo.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogoMouseClicked
    public static BufferedImage fotoSeleccionada;
    private void BotonURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonURLActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        String rutaCarpeta = "src/images";
        File carpeta = new File(rutaCarpeta);
        fileChooser.setCurrentDirectory(carpeta);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            urlImagen = archivoSeleccionado.getName();
            try {
                fotoSeleccionada = ImageIO.read(archivoSeleccionado);
            } catch (IOException e) {
                System.out.println("Error al cargar la foto: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BotonURLActionPerformed

    private void BotonCrearTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearTareaActionPerformed
        // TODO add your handling code here:

        if (CampoNombre.getText() != null && CampoFecEntrega != null && CampoNotas.getText() != null) {

            Connection cn = conexion.Conexion.conectar();
            String empleados = String.join(",", empleadosAsignados);

            try {

                PreparedStatement ps = cn.prepareStatement("INSERT INTO tareas (Nombre, EmpleadosAsignados, FechaEntrega, Estado, Prioridad, Notas, URLArchivoAdjunto) VALUES (?, ?, ?, ?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);

                ps.setString(1, CampoNombre.getText());
                if (empleados != null) {
                    ps.setString(2, empleados);
                }
                ps.setString(3, CampoFecEntrega.getText());
                ps.setString(4, ComboBoxEstado.getSelectedItem().toString());
                ps.setString(5, ComboBoxPrioridad.getSelectedItem().toString());
                ps.setString(6, CampoNotas.getText());
                ps.setString(7, urlImagen);

                ps.executeUpdate();

                ResultSet rs = ps.getGeneratedKeys();

                if (rs.next()) {
                    idTarea = rs.getString(1);
                    AlmacenarTareas.idsTareas.add(idTarea);
                }

                if (idEmpleadosAsignados != null) {

                    for (String ids : idEmpleadosAsignados) {
                        String[] idsIndividuales = ids.split(",");

                        for (String idEmpleado : idsIndividuales) {
                            if (!idEmpleado.trim().isEmpty()) {

                                PreparedStatement ps2 = cn.prepareStatement("INSERT INTO empleados_Tareas(ID_Tarea, ID_Empleado) VALUES (?, ?)");
                                ps2.setString(1, idTarea);
                                ps2.setString(2, idEmpleado.trim());
                                ps2.executeUpdate();
                            }
                        }
                    }
                }

                JOptionPane.showMessageDialog(null, "Tarea agregada correctamente");

                if (GestionarProyecto.bandera == false) {
                    int numeroActualDeTareas = Integer.parseInt(CrearProyecto.LabelNumeroTareas.getText());
                    CrearProyecto.LabelNumeroTareas.setText(String.valueOf(numeroActualDeTareas + 1));
                }

                if (GestionarProyecto.bandera == true) {
                    int numeroActualEmpleados = Integer.parseInt(GestionarProyecto.LabelNumeroTareas.getText());
                    GestionarProyecto.LabelNumeroTareas.setText(String.valueOf(numeroActualEmpleados + 1));
                }

                int respuesta = JOptionPane.showOptionDialog(null, "¿Quiere agregar otra tarea al proyecto?", "Seleccione una opción", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null, null, null);

                if (respuesta == 0) {

                    CrearTarea crearT = new CrearTarea();
                    crearT.setVisible(true);
                    this.dispose();
                } else {
                    this.dispose();
                }

            } catch (SQLException e) {
                e.printStackTrace();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
        }
    }//GEN-LAST:event_BotonCrearTareaActionPerformed

    private void LabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolverMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_LabelVolverMouseClicked


    private void BotonAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
        Connection cn = conexion.Conexion.conectar();

        String[] partes = ComboBoxEmpleadoAsignado.getSelectedItem().toString().split(" ", -1);
        String nombre = partes[0];
        String apellidos = partes[1];
        try {
            PreparedStatement ps2 = cn.prepareStatement("SELECT ID FROM usuarios WHERE Nombre = ? AND Apellidos = ?");

            ps2.setString(1, nombre);
            ps2.setString(2, apellidos);

            ResultSet rs = ps2.executeQuery();
            if (rs.next()) {
                idEmpleadosAsignados.add(rs.getString(1));
            }

            JOptionPane.showMessageDialog(null, "El empleado " + ComboBoxEmpleadoAsignado.getSelectedItem().toString() + " ha sido agregado a esta tarea");
            int numeroActualEmpleados = Integer.parseInt(CampoEmpleados.getText());
            CampoEmpleados.setText(String.valueOf(numeroActualEmpleados + 1));

        } catch (SQLException e) {
            e.printStackTrace();
        }

        empleadosAsignados.add(ComboBoxEmpleadoAsignado.getSelectedItem().toString());
        ComboBoxEmpleadoAsignado.removeItemAt(ComboBoxEmpleadoAsignado.getSelectedIndex());
    }//GEN-LAST:event_BotonAgregarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarEmpleado;
    private javax.swing.JButton BotonCrearTarea;
    private javax.swing.JButton BotonURL;
    private javax.swing.JLabel CampoEmpleados;
    private javax.swing.JTextField CampoFecEntrega;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoNotas;
    private javax.swing.JComboBox<String> ComboBoxEmpleadoAsignado;
    private javax.swing.JComboBox<String> ComboBoxEstado;
    private javax.swing.JComboBox<String> ComboBoxPrioridad;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelVolver;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables
    String urlImagen;
    String estado;
    String tipoEmpleado;
    static String idTarea;
    ArrayList<String> empleadosAsignados = new ArrayList<String>();
    ArrayList<String> idEmpleadosAsignados = new ArrayList<String>();
}
