/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;


import java.awt.image.*;
import java.io.*;
import java.time.*;
import javax.imageio.*;
import java.awt.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class CrearSolicitud extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmpleado
     */
    public CrearSolicitud() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());
        CampoFechaInicio.setText(LocalDate.now().toString());

        Connection cn = conexion.Conexion.conectar();
        try {

            PreparedStatement ps = cn.prepareStatement("SELECT Nombre, Apellidos FROM usuarios WHERE Tipo = ?");
            ps.setString(1, "Administrador");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                ComboBoxEncargado.addItem(rs.getString(1) + " " + rs.getString(2));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelFondo = new javax.swing.JPanel();
        CampoFechaInicio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BotonEnviarSolicitud = new javax.swing.JButton();
        BotonFoto = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoMensaje = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        ComboBoxEstado = new javax.swing.JComboBox<>();
        ComboBoxEncargado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        LabelVolver1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoFechaInicio.setBackground(new java.awt.Color(92, 116, 118));
        CampoFechaInicio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoFechaInicio.setForeground(java.awt.Color.white);
        CampoFechaInicio.setDisabledTextColor(java.awt.Color.white);
        CampoFechaInicio.setEnabled(false);
        PanelFondo.add(CampoFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 260, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Fecha:");
        PanelFondo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        CampoNombre.setBackground(new java.awt.Color(92, 116, 118));
        CampoNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNombre.setForeground(java.awt.Color.white);
        PanelFondo.add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 270, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Mensaje:");
        PanelFondo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Título:");
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Archivo adjunto:");
        PanelFondo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        BotonEnviarSolicitud.setBackground(new java.awt.Color(87, 186, 144));
        BotonEnviarSolicitud.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonEnviarSolicitud.setForeground(java.awt.Color.white);
        BotonEnviarSolicitud.setText("Enviar solicitud");
        BotonEnviarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnviarSolicitudActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonEnviarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, 240, 60));

        BotonFoto.setBackground(new java.awt.Color(92, 116, 118));
        BotonFoto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonFoto.setForeground(java.awt.Color.white);
        BotonFoto.setText("Añadir archivo");
        BotonFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFotoActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 260, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("x");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        PanelFondo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, 20, 30));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 186, 144));
        jLabel4.setText("PlanifiKa");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel1.setForeground(java.awt.Color.white);
        PanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 230, 30));

        CampoMensaje.setBackground(new java.awt.Color(92, 116, 118));
        CampoMensaje.setColumns(20);
        CampoMensaje.setForeground(java.awt.Color.white);
        CampoMensaje.setRows(5);
        jScrollPane1.setViewportView(CampoMensaje);

        PanelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 230, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Estado:");
        PanelFondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, -1, -1));

        ComboBoxEstado.setBackground(new java.awt.Color(92, 116, 118));
        ComboBoxEstado.setForeground(java.awt.Color.white);
        ComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Retrasada", "Finalizada" }));
        ComboBoxEstado.setEnabled(false);
        PanelFondo.add(ComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 240, 40));

        ComboBoxEncargado.setBackground(new java.awt.Color(92, 116, 118));
        ComboBoxEncargado.setForeground(java.awt.Color.white);
        PanelFondo.add(ComboBoxEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 260, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Administrador:");
        PanelFondo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        LabelVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-hacia-atras.png"))); // NOI18N
        LabelVolver1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolver1MouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 70, 70));

        jLabel18.setBackground(new java.awt.Color(26, 46, 68));
        jLabel18.setOpaque(true);
        PanelFondo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static BufferedImage fotoSeleccionada;
    private void BotonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        String rutaCarpeta = "src/images";
        File carpeta = new File(rutaCarpeta);
        fileChooser.setCurrentDirectory(carpeta);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            urlImagen = archivoSeleccionado.getName();
            try {
                fotoSeleccionada = ImageIO.read(archivoSeleccionado);
                jLabel1.setText(urlImagen);
            } catch (IOException e) {
                System.out.println("Error al cargar la foto: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BotonFotoActionPerformed

    private void BotonEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnviarSolicitudActionPerformed
        // TODO add your handling code here:

        if (CampoNombre.getText() != null && CampoMensaje.getText() != null) {
            
            String itemSeleccionado = (String) ComboBoxEncargado.getSelectedItem();
            String[] partes = itemSeleccionado.split(" ");
            String nombre = partes[0];
            String apellido = partes[1];
            
            Connection cn = conexion.Conexion.conectar();
            try {

                PreparedStatement admin = cn.prepareStatement("SELECT ID FROM usuarios WHERE Nombre = ? AND Apellidos = ?");
                admin.setString(1, nombre);
                admin.setString(2, apellido);
                ResultSet rsA = admin.executeQuery();
                if (rsA.next()) {
                    idAdmin = rsA.getInt(1);
                }

                PreparedStatement ps = cn.prepareStatement("INSERT INTO solicitudes (Titulo, Mensaje, Fecha, Estado, URLArchivoAdjunto, ID_Empleado, ID_Administrador) VALUES (?, ?, ?, ?, ?, ?, ?)");

                ps.setString(1, CampoNombre.getText());
                ps.setString(2, CampoMensaje.getText());
                ps.setString(3, CampoFechaInicio.getText());
                ps.setString(4, ComboBoxEstado.getSelectedItem().toString());
                ps.setString(5, jLabel1.getText());
                ps.setInt(6, Login.idInicioSesion);
                ps.setInt(7, idAdmin);

                ps.executeUpdate();

                System.out.println("Solicitud enviada con éxito");
                 PanelEmpleado panelE = new PanelEmpleado();
                panelE.setVisible(true);
                this.dispose();

            } catch (SQLException e) {
                e.printStackTrace();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
        }
    }//GEN-LAST:event_BotonEnviarSolicitudActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogoMouseClicked

    private void LabelVolver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolver1MouseClicked
        // TODO add your handling code here:
        ConsultarSolicitudes consultarS = new ConsultarSolicitudes();
        consultarS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelVolver1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEnviarSolicitud;
    private javax.swing.JButton BotonFoto;
    private javax.swing.JTextField CampoFechaInicio;
    private javax.swing.JTextArea CampoMensaje;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JComboBox<String> ComboBoxEncargado;
    private javax.swing.JComboBox<String> ComboBoxEstado;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelVolver1;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    String urlImagen;
    String estado;
    String tipoEmpleado;
    int idAdmin;
}
