/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.*;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import org.jdatepicker.impl.*;

/**
 *
 * @author Hugo
 */
public class CrearProyecto extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmpleado
     */
    public CrearProyecto() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());

        Connection cn = conexion.Conexion.conectar();
        try {

            PreparedStatement ps = cn.prepareStatement("SELECT Nombre, Apellidos FROM usuarios WHERE Tipo = ?");
            ps.setString(1, "JefeProyecto");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                ComboBoxEncargado.addItem(rs.getString(1) + " " + rs.getString(2));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelFondo = new javax.swing.JPanel();
        CampoFechaEntrega = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BotonAñadirTareas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CampoDescripcion = new javax.swing.JTextField();
        LabelVolver = new javax.swing.JLabel();
        BotonCrearProyecto = new javax.swing.JButton();
        CheckTareas = new javax.swing.JCheckBox();
        LabelNumeroTareas = new javax.swing.JLabel();
        ComboBoxEncargado = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelLogo = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoFechaEntrega.setBackground(new java.awt.Color(92, 116, 118));
        CampoFechaEntrega.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoFechaEntrega.setForeground(java.awt.Color.white);
        CampoFechaEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoFechaEntregaMouseClicked(evt);
            }
        });
        CampoFechaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFechaEntregaActionPerformed(evt);
            }
        });
        PanelFondo.add(CampoFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 260, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Fecha de entrega:");
        PanelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        CampoNombre.setBackground(new java.awt.Color(92, 116, 118));
        CampoNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNombre.setForeground(java.awt.Color.white);
        PanelFondo.add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 270, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Encargado:");
        PanelFondo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Nombre:");
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        BotonAñadirTareas.setBackground(new java.awt.Color(87, 186, 144));
        BotonAñadirTareas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonAñadirTareas.setForeground(java.awt.Color.white);
        BotonAñadirTareas.setText("Añadir tareas al proyecto");
        BotonAñadirTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAñadirTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirTareasActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonAñadirTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 330, 60));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Descripción:");
        PanelFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        CampoDescripcion.setBackground(new java.awt.Color(92, 116, 118));
        CampoDescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoDescripcion.setForeground(java.awt.Color.white);
        PanelFondo.add(CampoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 250, -1));

        LabelVolver.setBackground(new java.awt.Color(87, 186, 144));
        LabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-hacia-atras.png"))); // NOI18N
        LabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolverMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 70, 70));

        BotonCrearProyecto.setBackground(new java.awt.Color(87, 186, 144));
        BotonCrearProyecto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonCrearProyecto.setForeground(java.awt.Color.white);
        BotonCrearProyecto.setText("Crear proyecto");
        BotonCrearProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearProyectoActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonCrearProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 260, 60));

        CheckTareas.setBackground(new java.awt.Color(26, 46, 68));
        CheckTareas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CheckTareas.setForeground(java.awt.Color.white);
        CheckTareas.setText("Tareas añadidas:");
        CheckTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTareasActionPerformed(evt);
            }
        });
        PanelFondo.add(CheckTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, 30));

        LabelNumeroTareas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelNumeroTareas.setForeground(java.awt.Color.white);
        LabelNumeroTareas.setText("0");
        PanelFondo.add(LabelNumeroTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 20, 30));

        ComboBoxEncargado.setBackground(new java.awt.Color(92, 116, 118));
        ComboBoxEncargado.setForeground(java.awt.Color.white);
        PanelFondo.add(ComboBoxEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 260, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("x");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        PanelFondo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 20, 30));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 186, 144));
        jLabel4.setText("PlanifiKa");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel18.setBackground(new java.awt.Color(26, 46, 68));
        jLabel18.setOpaque(true);
        PanelFondo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolverMouseClicked
        // TODO add your handling code here:
        PanelJefeProyecto panelJP = new PanelJefeProyecto();
        panelJP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelVolverMouseClicked

    private void BotonAñadirTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirTareasActionPerformed
        // TODO add your handling code here:
        int seleccion = JOptionPane.showOptionDialog(null, "Seleccione opcion", "Selector de opciones", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Añadir tareas sueltas", "Añadir tareas nuevas"}, null);
        if (seleccion == 0) {
            try {
                Connection cn = conexion.Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement("SELECT * FROM tareas WHERE ID_Proyecto = NULL");
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    ConsultarTareasSueltas consultarTS = new ConsultarTareasSueltas();
                    consultarTS.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Todas las tareas creadas están asociadas en algún proyecto");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else if (seleccion == 1) {
            CrearTarea crearT = new CrearTarea();
            crearT.setVisible(true);
        }

    }//GEN-LAST:event_BotonAñadirTareasActionPerformed

    private void CampoFechaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFechaEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFechaEntregaActionPerformed


    private void BotonCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearProyectoActionPerformed
        // TODO add your handling code here:

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        fechaSeleccionada = LocalDate.parse(CampoFechaEntrega.getText(), formatter);
        fechaActual = LocalDate.now();

        if (fechaSeleccionada.isBefore(fechaActual)) {
            JOptionPane.showMessageDialog(null, "No puedes elegir una fecha de entrega anterior a la fecha actual");
        } else if (!CampoNombre.getText().isEmpty() && !CampoFechaEntrega.getText().isEmpty() && !CampoDescripcion.getText().isEmpty() && !ComboBoxEncargado.getSelectedItem().toString().isEmpty()) {

            if (CheckTareas.isSelected()) {

                Connection cn = conexion.Conexion.conectar();
                try {
                    String[] partes = ComboBoxEncargado.getSelectedItem().toString().split(" ", -1);
                    String nombre = partes[0];
                    String apellidos = partes[1];

                    PreparedStatement ps2 = cn.prepareStatement("SELECT ID FROM usuarios WHERE Nombre = ? AND Apellidos = ?");

                    ps2.setString(1, nombre);
                    ps2.setString(2, apellidos);

                    ResultSet rs = ps2.executeQuery();
                    if (rs.next()) {
                        idJefeP = rs.getInt(1);
                    }

                    PreparedStatement ps = cn.prepareStatement("INSERT INTO proyectos (Nombre, Descripcion, FechaEntrega, ID_JefeProyecto) VALUES (?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);

                    ps.setString(1, CampoFechaEntrega.getText());
                    ps.setString(2, CampoDescripcion.getText());
                    ps.setString(3, CampoFechaEntrega.getText());
                    ps.setInt(4, idJefeP);

                    ps.executeUpdate();

                    ResultSet generarId = ps.getGeneratedKeys();
                    if (generarId.next()) {
                        idProyecto = generarId.getInt(1);
                    }

                    if (AlmacenarTareas.idsTareas != null) {

                        for (String ids : AlmacenarTareas.idsTareas) {
                            String[] idsIndividuales = ids.split(",");
                            for (String idTarea : idsIndividuales) {
                                if (!idTarea.trim().isEmpty()) {
                                    PreparedStatement ps3 = cn.prepareStatement("UPDATE tareas SET ID_Proyecto = ? WHERE ID = ?");
                                    ps3.setInt(1, idProyecto);
                                    int idTareaInt = Integer.parseInt(idTarea.trim());
                                    ps3.setInt(2, idTareaInt);

                                    ps3.executeUpdate();
                                }
                            }
                        }
                    }

                    JOptionPane.showMessageDialog(null, "Proyecto creado con éxito");
                    PanelJefeProyecto panelJP = new PanelJefeProyecto();
                    panelJP.setVisible(true);
                    this.dispose();

                } catch (SQLException e) {
                    e.printStackTrace();

                }
            } else {
                JOptionPane.showMessageDialog(null, "Debes confirmar que las tareas necesarias han sido añadidas");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
        }

    }//GEN-LAST:event_BotonCrearProyectoActionPerformed

    private void CheckTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckTareasActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogoMouseClicked

    private void CampoFechaEntregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoFechaEntregaMouseClicked
        // TODO add your handling code here:
        JDialog dialog = new JDialog();
        dialog.setTitle("Seleccione una fecha");
        dialog.setModal(true);
        dialog.setUndecorated(true); 
        dialog.setLayout(new BorderLayout());

        UtilDateModel model = new UtilDateModel();
        Properties p = new Properties();
        p.put("text.today", "Hoy");
        p.put("text.month", "Mes");
        p.put("text.year", "Año");

        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

        dialog.add(datePicker, BorderLayout.CENTER);

        datePicker.addActionListener(e1 -> {
            CampoFechaEntrega.setText(datePicker.getJFormattedTextField().getText());
            dialog.dispose();
        });

        Point location = CampoFechaEntrega.getLocationOnScreen();
        dialog.setLocation(location.x, location.y + CampoFechaEntrega.getHeight());

        dialog.pack();

        dialog.setVisible(true);
    }//GEN-LAST:event_CampoFechaEntregaMouseClicked

    public static class DateLabelFormatter extends JFormattedTextField.AbstractFormatter {

        private String datePattern = "yyyy-MM-dd";
        private SimpleDateFormat dateFormatter = new SimpleDateFormat(datePattern);

        @Override
        public Object stringToValue(String text) throws ParseException {
            return dateFormatter.parseObject(text);
        }

        @Override
        public String valueToString(Object value) throws ParseException {
            if (value != null) {
                Calendar cal = (Calendar) value;
                return dateFormatter.format(cal.getTime());
            }
            return "";

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadirTareas;
    private javax.swing.JButton BotonCrearProyecto;
    private javax.swing.JTextField CampoDescripcion;
    private javax.swing.JTextField CampoFechaEntrega;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JCheckBox CheckTareas;
    private javax.swing.JComboBox<String> ComboBoxEncargado;
    private javax.swing.JLabel LabelLogo;
    public static javax.swing.JLabel LabelNumeroTareas;
    private javax.swing.JLabel LabelVolver;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    String urlImagen;
    String estado;
    String tipoEmpleado;
    int idProyecto;
    int idJefeP;

    LocalDate fechaSeleccionada;
    LocalDate fechaActual;
}
