/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sun.security.rsa.RSACore;
import sun.security.timestamp.TSRequest;

/**
 *
 * @author Hugo
 */
public class GestionarTarea extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmpleado
     */
    public GestionarTarea() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());

        Connection cn = conexion.Conexion.conectar();
        try {

            PreparedStatement ps = cn.prepareStatement("SELECT ID, Nombre, EmpleadosAsignados, FechaEntrega, Estado, Prioridad, Notas, URLArchivoAdjunto, ID_Proyecto FROM tareas WHERE ID = ?");
            ps.setString(1, ConsultarTareas.idSeleccionado);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                idTarea = rs.getString(1);
                CampoID.setText(rs.getString(1));
                CampoNombre.setText(rs.getString(2));
                CampoFecEntrega.setText(rs.getString(4));
                ComboBoxEstado.setSelectedItem(rs.getString(5));
                ComboBoxPrioridad.setSelectedItem(rs.getString(6));
                CampoNotas.setText(rs.getString(7));
                CampoIDProyecto.setText(rs.getString(9));

            }

            PreparedStatement ps4 = cn.prepareStatement("SELECT u.ID, u.Nombre, u.Apellidos FROM usuarios AS u INNER JOIN empleados_Tareas AS et ON u.ID = et.ID_Empleado INNER JOIN tareas AS t ON et.ID_Tarea = t.ID WHERE et.ID_Tarea = ?");
            ps4.setString(1, idTarea);

            ResultSet rs4 = ps4.executeQuery();
            while (rs4.next()) {
                idsAExcluir.add(rs4.getString(1));
                ComboBoxEmpleadoAsignado.addItem(rs4.getString(2) + " " + rs4.getString(3));
            }

            PreparedStatement ps2 = cn.prepareStatement("SELECT ID, Nombre, Apellidos FROM usuarios WHERE Tipo = ?");
            ps2.setString(1, "Empleado");

            ResultSet rs2 = ps2.executeQuery();
            while (rs2.next()) {
                String idActual = rs2.getString(1);
                if (!idsAExcluir.contains(idActual)) {
                    ComboBoxEmpleadoDisponible.addItem(rs2.getString(2) + " " + rs2.getString(3));
                }

            }

            PreparedStatement ps3 = cn.prepareStatement("SELECT COUNT(ID_Empleado) FROM empleados_Tareas WHERE ID_Tarea = ?");
            ps3.setString(1, idTarea);
            ResultSet rs3 = ps3.executeQuery();
            while (rs3.next()) {
                CampoEmpleados.setText(rs3.getString(1));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelFondo = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoIDProyecto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CampoID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CampoNotas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ComboBoxEmpleadoAsignado = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BotonEliminarEmpleado = new javax.swing.JButton();
        BotonModificarTarea = new javax.swing.JButton();
        BotonURL = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CampoFecEntrega = new javax.swing.JTextField();
        ComboBoxEmpleadoDisponible = new javax.swing.JComboBox<>();
        LabelVolver = new javax.swing.JLabel();
        BotonAgregarEmpleado = new javax.swing.JButton();
        ComboBoxPrioridad = new javax.swing.JComboBox<>();
        ComboBoxEstado = new javax.swing.JComboBox<>();
        CampoEmpleados = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CheckBoxModificar = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("PlanifiKa");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 40));

        CampoIDProyecto.setBackground(java.awt.Color.white);
        CampoIDProyecto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoIDProyecto.setForeground(java.awt.Color.black);
        CampoIDProyecto.setEnabled(false);
        PanelFondo.add(CampoIDProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 110, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("ID proyecto:");
        PanelFondo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Notas:");
        PanelFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, -1, -1));

        CampoID.setBackground(java.awt.Color.white);
        CampoID.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoID.setForeground(java.awt.Color.black);
        CampoID.setEnabled(false);
        PanelFondo.add(CampoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("ID:");
        PanelFondo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        CampoNotas.setBackground(java.awt.Color.white);
        CampoNotas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNotas.setForeground(java.awt.Color.black);
        CampoNotas.setEnabled(false);
        PanelFondo.add(CampoNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 270, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Estado:");
        PanelFondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Prioridad:");
        PanelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        CampoNombre.setBackground(java.awt.Color.white);
        CampoNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNombre.setForeground(java.awt.Color.black);
        CampoNombre.setEnabled(false);
        PanelFondo.add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 270, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Nombre:");
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        ComboBoxEmpleadoAsignado.setBackground(java.awt.Color.white);
        ComboBoxEmpleadoAsignado.setForeground(java.awt.Color.black);
        ComboBoxEmpleadoAsignado.setEnabled(false);
        PanelFondo.add(ComboBoxEmpleadoAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 250, 40));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Empleados asignados:");
        PanelFondo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("URL archivo adjunto:");
        PanelFondo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Empleados disponibles:");
        PanelFondo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, -1, -1));

        BotonEliminarEmpleado.setBackground(java.awt.Color.white);
        BotonEliminarEmpleado.setForeground(java.awt.Color.black);
        BotonEliminarEmpleado.setText("Descartar empleado");
        BotonEliminarEmpleado.setEnabled(false);
        BotonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarEmpleadoActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));

        BotonModificarTarea.setBackground(new java.awt.Color(102, 39, 40));
        BotonModificarTarea.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonModificarTarea.setForeground(java.awt.Color.white);
        BotonModificarTarea.setText("Modificar tarea");
        BotonModificarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModificarTarea.setEnabled(false);
        BotonModificarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarTareaActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonModificarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 240, 60));

        BotonURL.setBackground(java.awt.Color.white);
        BotonURL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonURL.setForeground(java.awt.Color.black);
        BotonURL.setText("Cambiar foto");
        BotonURL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonURL.setEnabled(false);
        BotonURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonURLActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 260, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Fecha de entrega:");
        PanelFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        CampoFecEntrega.setBackground(java.awt.Color.white);
        CampoFecEntrega.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoFecEntrega.setForeground(java.awt.Color.black);
        CampoFecEntrega.setEnabled(false);
        PanelFondo.add(CampoFecEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 250, -1));

        ComboBoxEmpleadoDisponible.setBackground(java.awt.Color.white);
        ComboBoxEmpleadoDisponible.setForeground(java.awt.Color.black);
        ComboBoxEmpleadoDisponible.setEnabled(false);
        ComboBoxEmpleadoDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEmpleadoDisponibleActionPerformed(evt);
            }
        });
        PanelFondo.add(ComboBoxEmpleadoDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, 270, 40));

        LabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volveratras.png"))); // NOI18N
        LabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolverMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 70, 70));

        BotonAgregarEmpleado.setBackground(java.awt.Color.white);
        BotonAgregarEmpleado.setForeground(java.awt.Color.black);
        BotonAgregarEmpleado.setText("Agregar empleado");
        BotonAgregarEmpleado.setEnabled(false);
        BotonAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarEmpleadoActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, -1, -1));

        ComboBoxPrioridad.setBackground(java.awt.Color.white);
        ComboBoxPrioridad.setForeground(java.awt.Color.black);
        ComboBoxPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));
        ComboBoxPrioridad.setEnabled(false);
        PanelFondo.add(ComboBoxPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 250, 40));

        ComboBoxEstado.setBackground(java.awt.Color.white);
        ComboBoxEstado.setForeground(java.awt.Color.black);
        ComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retrasada", "Pendiente", "Finalizada" }));
        ComboBoxEstado.setEnabled(false);
        PanelFondo.add(ComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 250, 40));

        CampoEmpleados.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CampoEmpleados.setForeground(java.awt.Color.white);
        CampoEmpleados.setText("0");
        PanelFondo.add(CampoEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 400, 30, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Empleados añadidos: ");
        PanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, -1, 20));

        CheckBoxModificar.setBackground(java.awt.Color.white);
        CheckBoxModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CheckBoxModificar.setForeground(java.awt.Color.black);
        CheckBoxModificar.setText("Modificar");
        CheckBoxModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckBoxModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxModificarActionPerformed(evt);
            }
        });
        PanelFondo.add(CheckBoxModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("x");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        PanelFondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 20, 20, 30));

        jLabel19.setBackground(new java.awt.Color(147, 63, 63));
        jLabel19.setForeground(new java.awt.Color(147, 63, 63));
        jLabel19.setOpaque(true);
        PanelFondo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogoMouseClicked
    public static BufferedImage fotoSeleccionada;
    private void BotonURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonURLActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        String rutaCarpeta = "src/images";
        File carpeta = new File(rutaCarpeta);
        fileChooser.setCurrentDirectory(carpeta);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            urlImagen = archivoSeleccionado.getName();
            try {
                fotoSeleccionada = ImageIO.read(archivoSeleccionado);
            } catch (IOException e) {
                System.out.println("Error al cargar la foto: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BotonURLActionPerformed

    private void BotonModificarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarTareaActionPerformed
        // TODO add your handling code here:

        Connection cn = conexion.Conexion.conectar();
        String empleados = String.join(",", empleadosAsignados);

        try {

            PreparedStatement ps = cn.prepareStatement("UPDATE tareas SET Nombre = ?, EmpleadosAsignados = ?, FechaEntrega = ?, Estado = ?, Prioridad = ?, Notas = ?, URLArchivoAdjunto = ? WHERE ID = ?");

            ps.setString(1, CampoNombre.getText());
            if (empleados != null) {
                ps.setString(2, empleados);
            }
            ps.setString(3, CampoFecEntrega.getText());
            ps.setString(4, ComboBoxEstado.getSelectedItem().toString());
            ps.setString(5, ComboBoxPrioridad.getSelectedItem().toString());
            ps.setString(6, CampoNotas.getText());
            ps.setString(7, urlImagen);
            ps.setString(8, idTarea);

            ps.executeUpdate();

            if (idEmpleadosNuevos != null) {

                for (String ids : idEmpleadosNuevos) {
                    String[] idsIndividuales = ids.split(",");

                    for (String idEmpleado : idsIndividuales) {
                        if (!idEmpleado.trim().isEmpty()) {

                            PreparedStatement ps2 = cn.prepareStatement("INSERT INTO empleados_Tareas(ID_Tarea, ID_Empleado) VALUES (?, ?)");
                            ps2.setString(1, idTarea);
                            ps2.setString(2, idEmpleado.trim());
                            ps2.executeUpdate();
                        }
                    }
                }
            }

            if (idEmpleadosAsignados != null) {

                for (String ids : idEmpleadosAsignados) {
                    String[] idsIndividuales = ids.split(",");

                    for (String idEmpleado : idsIndividuales) {
                        if (!idEmpleado.trim().isEmpty()) {

                            PreparedStatement ps2 = cn.prepareStatement("DELETE FROM empleados_Tareas WHERE ID_Empleado = ?");
                            ps2.setString(1, idEmpleado.trim());

                            ps2.executeUpdate();
                        }
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "Tarea actualizada correctamente");

            ConsultarTareas consultarT = new ConsultarTareas();
            consultarT.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_BotonModificarTareaActionPerformed

    private void LabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolverMouseClicked
        // TODO add your handling code here:
        ConsultarTareas consultarT = new ConsultarTareas();
        consultarT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelVolverMouseClicked


    private void BotonAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
        Connection cn = conexion.Conexion.conectar();

        String[] partes = ComboBoxEmpleadoDisponible.getSelectedItem().toString().split(" ", -1);
        String nombre = partes[0];
        String apellidos = partes[1];
        try {
            PreparedStatement ps2 = cn.prepareStatement("SELECT ID FROM usuarios WHERE Nombre = ? AND Apellidos = ?");

            ps2.setString(1, nombre);
            ps2.setString(2, apellidos);

            ResultSet rs = ps2.executeQuery();
            if (rs.next()) {
                idEmpleadosNuevos.add(rs.getString(1));
            }

            JOptionPane.showMessageDialog(null, "El empleado " + ComboBoxEmpleadoDisponible.getSelectedItem().toString() + " ha sido agregado a esta tarea");
            int numeroActualEmpleados = Integer.parseInt(CampoEmpleados.getText());
            CampoEmpleados.setText(String.valueOf(numeroActualEmpleados + 1));

        } catch (SQLException e) {
            e.printStackTrace();
        }

        empleadosAsignados.add(ComboBoxEmpleadoDisponible.getSelectedItem().toString());
        ComboBoxEmpleadoDisponible.removeItemAt(ComboBoxEmpleadoDisponible.getSelectedIndex());
    }//GEN-LAST:event_BotonAgregarEmpleadoActionPerformed

    private void CheckBoxModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxModificarActionPerformed
        // TODO add your handling code here:
        if (CheckBoxModificar.isSelected()) {
            CampoNombre.setEnabled(true);
            CampoFecEntrega.setEnabled(true);
            CampoNotas.setEnabled(true);
            ComboBoxEstado.setEnabled(true);
            ComboBoxPrioridad.setEnabled(true);
            ComboBoxEmpleadoDisponible.setEnabled(true);
            BotonAgregarEmpleado.setEnabled(true);
            BotonModificarTarea.setEnabled(true);
            BotonURL.setEnabled(true);
            ComboBoxEmpleadoAsignado.setEnabled(true);
            BotonEliminarEmpleado.setEnabled(true);
        }
        if (!CheckBoxModificar.isSelected()) {
            CampoNombre.setEnabled(false);
            CampoFecEntrega.setEnabled(false);
            CampoNotas.setEnabled(false);
            ComboBoxEstado.setEnabled(false);
            ComboBoxPrioridad.setEnabled(false);
            ComboBoxEmpleadoDisponible.setEnabled(false);
            BotonAgregarEmpleado.setEnabled(false);
            BotonModificarTarea.setEnabled(false);
            BotonURL.setEnabled(false);
            ComboBoxEmpleadoAsignado.setEnabled(false);
            BotonEliminarEmpleado.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBoxModificarActionPerformed

    private void BotonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
        Connection cn = conexion.Conexion.conectar();
        String[] partes = ComboBoxEmpleadoAsignado.getSelectedItem().toString().split(" ", -1);
        String nombre = partes[0];
        String apellidos = partes[1];
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT ID FROM usuarios WHERE Nombre = ? AND Apellidos = ?");

            ps.setString(1, nombre);
            ps.setString(2, apellidos);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                idEmpleado = rs.getString(1);
                idEmpleadosAsignados.add(rs.getString(1));
            }

            JOptionPane.showMessageDialog(null, "El empleado " + ComboBoxEmpleadoDisponible.getSelectedItem().toString() + " ha sido eliminado de esta tarea");
            int numeroActualEmpleados = Integer.parseInt(CampoEmpleados.getText());
            CampoEmpleados.setText(String.valueOf(numeroActualEmpleados - 1));

            ComboBoxEmpleadoAsignado.removeItemAt(ComboBoxEmpleadoAsignado.getSelectedIndex());

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BotonEliminarEmpleadoActionPerformed

    private void ComboBoxEmpleadoDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEmpleadoDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEmpleadoDisponibleActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarEmpleado;
    private javax.swing.JButton BotonEliminarEmpleado;
    private javax.swing.JButton BotonModificarTarea;
    private javax.swing.JButton BotonURL;
    private javax.swing.JLabel CampoEmpleados;
    private javax.swing.JTextField CampoFecEntrega;
    private javax.swing.JTextField CampoID;
    private javax.swing.JTextField CampoIDProyecto;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoNotas;
    private javax.swing.JCheckBox CheckBoxModificar;
    private javax.swing.JComboBox<String> ComboBoxEmpleadoAsignado;
    private javax.swing.JComboBox<String> ComboBoxEmpleadoDisponible;
    private javax.swing.JComboBox<String> ComboBoxEstado;
    private javax.swing.JComboBox<String> ComboBoxPrioridad;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelVolver;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    String urlImagen;
    String estado;
    String tipoEmpleado;
    static String idTarea;
    String idEmpleado;
    ArrayList<String> empleadosAsignados = new ArrayList<String>();
    ArrayList<String> idEmpleadosAsignados = new ArrayList<String>();

    ArrayList<String> idEmpleadosNuevos = new ArrayList<String>();
    ArrayList<String> idsAExcluir = new ArrayList<String>();
}
