/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo
 */
public class GestionarProyecto extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmpleado
     */
    public GestionarProyecto() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());

        Connection cn = conexion.Conexion.conectar();
        try {

            PreparedStatement ps = cn.prepareStatement("SELECT ID, Nombre, Descripcion, FechaEntrega, ID_JefeProyecto FROM proyectos WHERE ID = ?");
            ps.setString(1, ConsultarProyectos.idSeleccionado);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                idProyectoActual = rs.getInt(1);
                CampoID.setText(rs.getString(1));
                CampoNombre.setText(rs.getString(2));
                CampoDescripcion.setText(rs.getString(3));
                CampoFechaEntrega.setText(rs.getString(4));
                CampoIDJefeProyecto.setText(rs.getString(5));
            }

            PreparedStatement ps2 = cn.prepareStatement("SELECT COUNT(ID) FROM tareas WHERE ID_Proyecto = ?");
            ps2.setString(1, ConsultarProyectos.idSeleccionado);

            ResultSet rs2 = ps2.executeQuery();
            while (rs2.next()) {
                LabelNumeroTareas.setText(rs2.getString(1));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelFondo = new javax.swing.JPanel();
        CampoID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LabelLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoFechaEntrega = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BotonAñadirTareas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CampoDescripcion = new javax.swing.JTextField();
        LabelVolver = new javax.swing.JLabel();
        BotonModificarProyecto = new javax.swing.JButton();
        LabelNumeroTareas = new javax.swing.JLabel();
        CampoIDJefeProyecto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CheckBoxModificar = new javax.swing.JCheckBox();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoID.setBackground(java.awt.Color.black);
        CampoID.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoID.setForeground(java.awt.Color.white);
        CampoID.setEnabled(false);
        PanelFondo.add(CampoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 90, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("ID");
        PanelFondo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("PlanifiKa");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 40));

        CampoFechaEntrega.setBackground(java.awt.Color.black);
        CampoFechaEntrega.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoFechaEntrega.setForeground(java.awt.Color.white);
        CampoFechaEntrega.setEnabled(false);
        CampoFechaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFechaEntregaActionPerformed(evt);
            }
        });
        PanelFondo.add(CampoFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 260, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Fecha de entrega:");
        PanelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        CampoNombre.setBackground(java.awt.Color.black);
        CampoNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNombre.setForeground(java.awt.Color.white);
        CampoNombre.setEnabled(false);
        PanelFondo.add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 270, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Nombre:");
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        BotonAñadirTareas.setBackground(java.awt.Color.black);
        BotonAñadirTareas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonAñadirTareas.setForeground(java.awt.Color.white);
        BotonAñadirTareas.setText("Añadir tareas al proyecto");
        BotonAñadirTareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAñadirTareas.setEnabled(false);
        BotonAñadirTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirTareasActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonAñadirTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 340, 60));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Descripción:");
        PanelFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        CampoDescripcion.setBackground(java.awt.Color.black);
        CampoDescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoDescripcion.setForeground(java.awt.Color.white);
        CampoDescripcion.setEnabled(false);
        PanelFondo.add(CampoDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 250, -1));

        LabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volveratras.png"))); // NOI18N
        LabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolverMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 70, 70));

        BotonModificarProyecto.setBackground(java.awt.Color.black);
        BotonModificarProyecto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonModificarProyecto.setForeground(java.awt.Color.white);
        BotonModificarProyecto.setText("Modificar proyecto");
        BotonModificarProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModificarProyecto.setEnabled(false);
        BotonModificarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarProyectoActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonModificarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 330, 60));

        LabelNumeroTareas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelNumeroTareas.setForeground(java.awt.Color.white);
        LabelNumeroTareas.setText("0");
        PanelFondo.add(LabelNumeroTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 20, 30));

        CampoIDJefeProyecto.setBackground(java.awt.Color.black);
        CampoIDJefeProyecto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoIDJefeProyecto.setForeground(java.awt.Color.white);
        CampoIDJefeProyecto.setEnabled(false);
        PanelFondo.add(CampoIDJefeProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 250, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("ID Jefe de proyecto:");
        PanelFondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Tareas añadidas:");
        PanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, 30));

        CheckBoxModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CheckBoxModificar.setForeground(java.awt.Color.white);
        CheckBoxModificar.setText("Modificar");
        CheckBoxModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckBoxModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxModificarActionPerformed(evt);
            }
        });
        PanelFondo.add(CheckBoxModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, -1, -1));

        labelFondo.setBackground(java.awt.Color.black);
        labelFondo.setForeground(java.awt.Color.white);
        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondotfg.png"))); // NOI18N
        PanelFondo.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolverMouseClicked
        // TODO add your handling code here:
        int respuesta = JOptionPane.showOptionDialog(null, "¿Desea salir sin modificar el proyecto?", "Decisión", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null, null, NORMAL);
        if (respuesta == 0) {
            ConsultarProyectos consultarP = new ConsultarProyectos();
            consultarP.setVisible(true);
            bandera = false;
            this.dispose();
        }

    }//GEN-LAST:event_LabelVolverMouseClicked

    private void BotonAñadirTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirTareasActionPerformed
        // TODO add your handling code here:
        int seleccion = JOptionPane.showOptionDialog(null, "Seleccione opcion", "Selector de opciones", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Añadir tareas sueltas", "Añadir tareas nuevas"}, null);
        if (seleccion == 0) {
            try {
                Connection cn = conexion.Conexion.conectar();
                PreparedStatement ps = cn.prepareStatement("SELECT * FROM tareas WHERE ID_Proyecto IS NULL");
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    ConsultarTareasSueltas consultarTS = new ConsultarTareasSueltas();
                    consultarTS.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Todas las tareas creadas están asociadas en algún proyecto");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else if (seleccion == 1) {
            CrearTarea crearT = new CrearTarea();
            bandera = true;
            crearT.setVisible(true);
        }


    }//GEN-LAST:event_BotonAñadirTareasActionPerformed

    private void CampoFechaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFechaEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFechaEntregaActionPerformed

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogoMouseClicked


    private void BotonModificarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarProyectoActionPerformed
        // TODO add your handling code here:

        Connection cn = conexion.Conexion.conectar();
        try {

            PreparedStatement ps = cn.prepareStatement("UPDATE proyectos SET Nombre = ?, Descripcion = ?, FechaEntrega = ?, ID_JefeProyecto = ? WHERE ID = ?");

            ps.setString(1, CampoNombre.getText());
            ps.setString(2, CampoDescripcion.getText());
            ps.setString(3, CampoFechaEntrega.getText());
            ps.setString(4, CampoIDJefeProyecto.getText());
            ps.setInt(5, idProyectoActual);

            ps.executeUpdate();

            if (AlmacenarTareas.idsTareas != null) {

                for (String ids : AlmacenarTareas.idsTareas) {
                    String[] idsIndividuales = ids.split(",");
                    for (String idTarea : idsIndividuales) {
                        if (!idTarea.trim().isEmpty()) {
                            PreparedStatement ps3 = cn.prepareStatement("UPDATE tareas SET ID_Proyecto = ? WHERE ID = ?");
                            ps3.setInt(1, idProyectoActual);
                            int idTareaInt = Integer.parseInt(idTarea.trim());
                            ps3.setInt(2, idTareaInt);

                            ps3.executeUpdate();
                        }
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "Proyecto modificado con éxito");
            ConsultarProyectos consultarP = new ConsultarProyectos();
            consultarP.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_BotonModificarProyectoActionPerformed

    private void CheckBoxModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxModificarActionPerformed
        // TODO add your handling code here:
        if (CheckBoxModificar.isSelected()) {
            CampoNombre.setEnabled(true);
            CampoDescripcion.setEnabled(true);
            CampoFechaEntrega.setEnabled(true);
            CampoIDJefeProyecto.setEnabled(true);
            BotonAñadirTareas.setEnabled(true);
            BotonModificarProyecto.setEnabled(true);
        }
        if (!CheckBoxModificar.isSelected()) {
            CampoNombre.setEnabled(false);
            CampoDescripcion.setEnabled(false);
            CampoFechaEntrega.setEnabled(false);
            CampoIDJefeProyecto.setEnabled(false);
            BotonAñadirTareas.setEnabled(false);
            BotonModificarProyecto.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBoxModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadirTareas;
    private javax.swing.JButton BotonModificarProyecto;
    private javax.swing.JTextField CampoDescripcion;
    private javax.swing.JTextField CampoFechaEntrega;
    public static javax.swing.JTextField CampoID;
    private javax.swing.JTextField CampoIDJefeProyecto;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JCheckBox CheckBoxModificar;
    private javax.swing.JLabel LabelLogo;
    public static javax.swing.JLabel LabelNumeroTareas;
    private javax.swing.JLabel LabelVolver;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables

    static int idProyectoActual;
    static boolean bandera;
}
