/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.*;
import java.awt.image.*;
import java.io.*;
import java.sql.*;
import javax.imageio.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class GestionarTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmpleado
     */
    public GestionarTrabajador() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());

        Connection cn = conexion.Conexion.conectar();
        
        try {

            PreparedStatement ps2 = cn.prepareStatement("SELECT * FROM usuarios WHERE ID = ?");
            ps2.setString(1, ConsultarTrabajadores.idSeleccionado);

            ResultSet rs2 = ps2.executeQuery();

            while (rs2.next()) {
                id = rs2.getString(1);
                dni = rs2.getString(2);
                nombre = rs2.getString(3);
                apellidos = rs2.getString(4);
                telefono = rs2.getString(5);
                email = rs2.getString(6);
                empresa = rs2.getString(7);
                direccion = rs2.getString(8);
                usuario = rs2.getString(9);
                contrasena = rs2.getString(10);
                estado = rs2.getString(11);
                tipoEmpleado = rs2.getString(12);
                fechaInicio = rs2.getDate(13);
                agregadoPor = rs2.getString(14);
                urlImagen = rs2.getString(15);
            }

            rs2.close();
            ps2.close();

            if (estado.equals("Activo")) {
                BotonActivo.setSelected(true);
            }

            if (estado.equals("Inactivo")) {
                BotonInactivo.setSelected(true);
            }

            if (tipoEmpleado.equals("Administrador")) {
                ComboTipo.setSelectedIndex(0);
            }

            if (tipoEmpleado.equals("JefeProyecto")) {
                ComboTipo.setSelectedIndex(1);
            }

            if (tipoEmpleado.equals("Empleado")) {
                ComboTipo.setSelectedIndex(2);
            }

            CampoDNI.setText(dni);
            CampoNombre.setText(nombre);
            CampoApellidos.setText(apellidos);
            CampoTelefono.setText(telefono);
            CampoEmail.setText(email);
            CampoDireccion.setText(direccion);
            CampoFechaInicio.setText(fechaInicio.toString());
            ComboBoxAgregadoPor.addItem(agregadoPor);
            LabelURL.setText(urlImagen);
            CampoID.setText(id);
            CampoEmpresa.setText(empresa);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelFondo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CampoEmpresa = new javax.swing.JTextField();
        CampoTelefono = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CampoDireccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CampoID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CampoFechaInicio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CampoDNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BotonEstadisticas = new javax.swing.JButton();
        BotonModificarEmpleado = new javax.swing.JButton();
        BotonFoto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CampoApellidos = new javax.swing.JTextField();
        ComboTipo = new javax.swing.JComboBox<>();
        BotonActivo = new javax.swing.JRadioButton();
        BotonInactivo = new javax.swing.JRadioButton();
        ComboBoxAgregadoPor = new javax.swing.JComboBox<>();
        BotonBaja = new javax.swing.JButton();
        CheckBoxModificar = new javax.swing.JCheckBox();
        BotonSolicitudes = new javax.swing.JButton();
        LabelURL = new javax.swing.JLabel();
        LabelVolver = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelLogo = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Teléfono:");
        PanelFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Correo electrónico:");
        PanelFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        CampoEmpresa.setBackground(new java.awt.Color(92, 116, 118));
        CampoEmpresa.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoEmpresa.setForeground(java.awt.Color.white);
        CampoEmpresa.setDisabledTextColor(java.awt.Color.white);
        CampoEmpresa.setEnabled(false);
        PanelFondo.add(CampoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 250, -1));

        CampoTelefono.setBackground(new java.awt.Color(92, 116, 118));
        CampoTelefono.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoTelefono.setForeground(java.awt.Color.white);
        CampoTelefono.setDisabledTextColor(java.awt.Color.white);
        CampoTelefono.setEnabled(false);
        PanelFondo.add(CampoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 250, -1));

        CampoEmail.setBackground(new java.awt.Color(92, 116, 118));
        CampoEmail.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoEmail.setForeground(java.awt.Color.white);
        CampoEmail.setDisabledTextColor(java.awt.Color.white);
        CampoEmail.setEnabled(false);
        PanelFondo.add(CampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 250, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Empresa:");
        PanelFondo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Estado:");
        PanelFondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        CampoDireccion.setBackground(new java.awt.Color(92, 116, 118));
        CampoDireccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoDireccion.setForeground(java.awt.Color.white);
        CampoDireccion.setDisabledTextColor(java.awt.Color.white);
        CampoDireccion.setEnabled(false);
        CampoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDireccionActionPerformed(evt);
            }
        });
        PanelFondo.add(CampoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 260, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Dirección:");
        PanelFondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, -1, -1));

        CampoID.setBackground(new java.awt.Color(92, 116, 118));
        CampoID.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoID.setForeground(java.awt.Color.white);
        CampoID.setDisabledTextColor(java.awt.Color.white);
        CampoID.setEnabled(false);
        CampoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIDActionPerformed(evt);
            }
        });
        PanelFondo.add(CampoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 80, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("ID:");
        PanelFondo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, -1));

        CampoFechaInicio.setBackground(new java.awt.Color(92, 116, 118));
        CampoFechaInicio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoFechaInicio.setForeground(java.awt.Color.white);
        CampoFechaInicio.setDisabledTextColor(java.awt.Color.white);
        CampoFechaInicio.setEnabled(false);
        PanelFondo.add(CampoFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, 260, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Fecha de inicio:");
        PanelFondo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Tipo:");
        PanelFondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        CampoDNI.setBackground(new java.awt.Color(92, 116, 118));
        CampoDNI.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoDNI.setForeground(java.awt.Color.white);
        CampoDNI.setDisabledTextColor(java.awt.Color.white);
        CampoDNI.setEnabled(false);
        CampoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDNIActionPerformed(evt);
            }
        });
        PanelFondo.add(CampoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 250, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("DNI:");
        PanelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        CampoNombre.setBackground(new java.awt.Color(92, 116, 118));
        CampoNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNombre.setForeground(java.awt.Color.white);
        CampoNombre.setDisabledTextColor(java.awt.Color.white);
        CampoNombre.setEnabled(false);
        PanelFondo.add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 270, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Nombre:");
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Foto:");
        PanelFondo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Agregado por:");
        PanelFondo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, -1, -1));

        BotonEstadisticas.setBackground(new java.awt.Color(87, 186, 144));
        BotonEstadisticas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonEstadisticas.setForeground(java.awt.Color.white);
        BotonEstadisticas.setText("Estadísticas");
        BotonEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstadisticasActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 730, 190, 60));

        BotonModificarEmpleado.setBackground(new java.awt.Color(87, 186, 144));
        BotonModificarEmpleado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonModificarEmpleado.setForeground(java.awt.Color.white);
        BotonModificarEmpleado.setText("Modificar empleado");
        BotonModificarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModificarEmpleado.setEnabled(false);
        BotonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarEmpleadoActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonModificarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 730, 290, 60));

        BotonFoto.setBackground(new java.awt.Color(92, 116, 118));
        BotonFoto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonFoto.setForeground(java.awt.Color.white);
        BotonFoto.setText("Cambiar foto");
        BotonFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonFoto.setEnabled(false);
        BotonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFotoActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 600, 260, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Apellidos:");
        PanelFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        CampoApellidos.setBackground(new java.awt.Color(92, 116, 118));
        CampoApellidos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoApellidos.setForeground(java.awt.Color.white);
        CampoApellidos.setDisabledTextColor(java.awt.Color.white);
        CampoApellidos.setEnabled(false);
        PanelFondo.add(CampoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 250, -1));

        ComboTipo.setBackground(new java.awt.Color(92, 116, 118));
        ComboTipo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboTipo.setForeground(java.awt.Color.white);
        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Jefe de proyecto", "Empleado" }));
        ComboTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboTipo.setEnabled(false);
        PanelFondo.add(ComboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 260, 40));

        BotonActivo.setBackground(new java.awt.Color(26, 46, 68));
        buttonGroup1.add(BotonActivo);
        BotonActivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonActivo.setForeground(java.awt.Color.white);
        BotonActivo.setText("Activo");
        BotonActivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonActivo.setEnabled(false);
        PanelFondo.add(BotonActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        BotonInactivo.setBackground(new java.awt.Color(26, 46, 68));
        buttonGroup1.add(BotonInactivo);
        BotonInactivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonInactivo.setForeground(java.awt.Color.white);
        BotonInactivo.setText("Inactivo");
        BotonInactivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInactivo.setEnabled(false);
        PanelFondo.add(BotonInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        ComboBoxAgregadoPor.setBackground(new java.awt.Color(92, 116, 118));
        ComboBoxAgregadoPor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboBoxAgregadoPor.setForeground(java.awt.Color.white);
        ComboBoxAgregadoPor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboBoxAgregadoPor.setEnabled(false);
        PanelFondo.add(ComboBoxAgregadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 270, 40));

        BotonBaja.setBackground(new java.awt.Color(87, 186, 144));
        BotonBaja.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonBaja.setForeground(java.awt.Color.white);
        BotonBaja.setText("Dar de baja");
        BotonBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 730, 190, 60));

        CheckBoxModificar.setBackground(new java.awt.Color(26, 46, 68));
        CheckBoxModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CheckBoxModificar.setForeground(java.awt.Color.white);
        CheckBoxModificar.setText("Modificar");
        CheckBoxModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckBoxModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxModificarActionPerformed(evt);
            }
        });
        PanelFondo.add(CheckBoxModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, -1, -1));

        BotonSolicitudes.setBackground(new java.awt.Color(87, 186, 144));
        BotonSolicitudes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonSolicitudes.setForeground(java.awt.Color.white);
        BotonSolicitudes.setText("Solicitudes");
        BotonSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSolicitudesActionPerformed(evt);
            }
        });
        PanelFondo.add(BotonSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 730, 190, 60));

        LabelURL.setForeground(java.awt.Color.white);
        PanelFondo.add(LabelURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, 260, 30));

        LabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-hacia-atras.png"))); // NOI18N
        LabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolverMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 70, 70));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("x");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        PanelFondo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 20, 20, 30));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 186, 144));
        jLabel4.setText("PlanifiKa");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel18.setBackground(new java.awt.Color(26, 46, 68));
        jLabel18.setOpaque(true);
        PanelFondo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDireccionActionPerformed

    private void CampoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDNIActionPerformed
    public static BufferedImage fotoSeleccionada;
    private void BotonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        String rutaCarpeta = "src/images";
        File carpeta = new File(rutaCarpeta);
        fileChooser.setCurrentDirectory(carpeta);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            urlImagen = archivoSeleccionado.getName();
            try {
                fotoSeleccionada = ImageIO.read(archivoSeleccionado);
                LabelURL.setText(urlImagen);
            } catch (IOException e) {
                System.out.println("Error al cargar la foto: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BotonFotoActionPerformed

    private void BotonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarEmpleadoActionPerformed
        // TODO add your handling code here:

        Connection cn = conexion.Conexion.conectar();
        if (BotonActivo.isSelected()) {
            estado = "Activo";
        }
        if (BotonInactivo.isSelected()) {
            estado = "Inactivo";
        }

        try {
            PreparedStatement ps = cn.prepareStatement("UPDATE usuarios SET DNI = ?, Nombre = ?, Apellidos = ?, Telefono = ?, Email = ?, Empresa = ?, Direccion = ?, Estado = ?, Tipo = ?, FechaInicio = ?, AgregadoPor = ?, URLFoto = ? WHERE ID = ?");

            ps.setString(1, CampoDNI.getText());
            ps.setString(2, CampoNombre.getText());
            ps.setString(3, CampoApellidos.getText());
            ps.setString(4, CampoTelefono.getText());
            ps.setString(5, CampoEmail.getText());
            ps.setString(6, CampoEmpresa.getText());
            ps.setString(7, CampoDireccion.getText());
            ps.setString(8, estado);
            ps.setString(9, ComboTipo.getSelectedItem().toString());
            ps.setString(10, CampoFechaInicio.getText());
            ps.setString(11, ComboBoxAgregadoPor.getSelectedItem().toString());
            ps.setString(12, urlImagen);
            ps.setString(13, ConsultarTrabajadores.idSeleccionado);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Trabajador modificado con éxito");
            ConsultarTrabajadores consultarT = new ConsultarTrabajadores();
            consultarT.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_BotonModificarEmpleadoActionPerformed

    private void CheckBoxModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxModificarActionPerformed
        // TODO add your handling code here:
        if (CheckBoxModificar.isSelected()) {
            CampoNombre.setEnabled(true);
            CampoApellidos.setEnabled(true);
            CampoEmail.setEnabled(true);
            CampoTelefono.setEnabled(true);
            CampoDireccion.setEnabled(true);
            BotonActivo.setEnabled(true);
            BotonInactivo.setEnabled(true);
            ComboTipo.setEnabled(true);
            CampoEmpresa.setEnabled(true);
            BotonFoto.setEnabled(true);
            BotonModificarEmpleado.setEnabled(true);
        }
        if (!CheckBoxModificar.isSelected()) {
            CampoNombre.setEnabled(false);
            CampoApellidos.setEnabled(false);
            CampoEmail.setEnabled(false);
            CampoTelefono.setEnabled(false);
            CampoDireccion.setEnabled(false);
            BotonActivo.setEnabled(false);
            BotonInactivo.setEnabled(false);
            ComboTipo.setEnabled(false);
            CampoEmpresa.setEnabled(false);
            BotonFoto.setEnabled(false);
            BotonModificarEmpleado.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBoxModificarActionPerformed

    private void BotonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstadisticasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Este apartado se añadirá en futuras actualizaciones");
    }//GEN-LAST:event_BotonEstadisticasActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        // TODO add your handling code here:

        Connection cn = conexion.Conexion.conectar();

        try {
            if (tipoEmpleado.equals("Empleado")) {
                PreparedStatement comprobarTareas = cn.prepareStatement("SELECT ID FROM empleados_Tareas WHERE ID_Empleado = ?");
                comprobarTareas.setString(1, CampoID.getText());

                ResultSet comprobar = comprobarTareas.executeQuery();

                while (comprobar.next()) {
                    contadorTareas++;
                    bandera = true;
                }
            }

            if (bandera == true) {
                int respuesta2 = JOptionPane.showOptionDialog(null, "Hay un problema. El empleado " + CampoNombre.getText() + " " + CampoApellidos.getText() + " con DNI: " + CampoDNI.getText() + " tiene " + contadorTareas + " tareas encargadas. ¿Desea desasignarselas?", "Confirmación de tareas", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null, null, NORMAL);

                if (respuesta2 == 0) {
                    int respuesta = JOptionPane.showOptionDialog(null, "¿Quieres dar de baja al empleado " + CampoNombre.getText() + " " + CampoApellidos.getText() + " con DNI: " + CampoDNI.getText() + " ?", "Confirmación de baja", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null, null, NORMAL);
                    if (respuesta == 0) {
                        try {
                            PreparedStatement ps = cn.prepareStatement("DELETE FROM usuarios WHERE ID = ?");
                            ps.setString(1, CampoID.getText());

                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Empleado eliminado con éxito");
                            ConsultarTrabajadores consultarT = new ConsultarTrabajadores();
                            consultarT.setVisible(true);
                            this.dispose();
                        } catch (SQLException e) {
                            e.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Has decidido no eliminar al empleado");
                        ConsultarTrabajadores consultarT = new ConsultarTrabajadores();
                        consultarT.setVisible(true);
                        this.dispose();
                    }
                }

                if (respuesta2 == 1) {
                    JOptionPane.showMessageDialog(null, "No puede eliminar al empleado si tiene tareas asociadas");
                }

                if (tipoEmpleado.equals("JefeProyecto")) {

                    PreparedStatement comprobarProyectos = cn.prepareStatement("SELECT ID FROM Proyectos WHERE ID_JefeProyecto = ?");
                    comprobarProyectos.setString(1, CampoID.getText());

                    ResultSet comprobar = comprobarProyectos.executeQuery();

                    while (comprobar.next()) {
                        contadorProyectos++;
                        banderaP = true;
                    }
                }
            }
            if (banderaP == true) {
                int respuesta3 = JOptionPane.showOptionDialog(null, "Hay un problema. El trabajador " + CampoNombre.getText() + " " + CampoApellidos.getText() + " con DNI: " + CampoDNI.getText() + " tiene " + contadorProyectos + " proyectos asociados. ¿Desea desasignarselos?", "Confirmación de proyectos", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null, null, NORMAL);

                if (respuesta3 == 0) {
                    int respuesta = JOptionPane.showOptionDialog(null, "¿Quieres dar de baja al jefe de proyecto " + CampoNombre.getText() + " " + CampoApellidos.getText() + " con DNI: " + CampoDNI.getText() + " ?", "Confirmación de baja", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null, null, NORMAL);
                    if (respuesta == 0) {
                        try {
                            PreparedStatement ps = cn.prepareStatement("DELETE FROM usuarios WHERE ID = ?");
                            ps.setString(1, CampoID.getText());

                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Jefe de proyecto eliminado con éxito");
                            ConsultarTrabajadores consultarT = new ConsultarTrabajadores();
                            consultarT.setVisible(true);
                            this.dispose();
                        } catch (SQLException e) {
                            e.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Has decidido no eliminar al jefe de proyecto");
                        ConsultarTrabajadores consultarT = new ConsultarTrabajadores();
                        consultarT.setVisible(true);
                        this.dispose();
                    }
                }

                if (respuesta3 == 1) {
                    JOptionPane.showMessageDialog(null, "No puede eliminar al empleado si tiene tareas asociadas");
                }

            } else {
                int respuesta = JOptionPane.showOptionDialog(null, "¿Quieres dar de baja al trabajador " + CampoNombre.getText() + " " + CampoApellidos.getText() + " con DNI: " + CampoDNI.getText() + " ?", "Confirmación de baja", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null, null, NORMAL);
                if (respuesta == 0) {
                    try {
                        PreparedStatement ps = cn.prepareStatement("DELETE FROM usuarios WHERE ID = ?");
                        ps.setString(1, CampoID.getText());

                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Trabajador eliminado con éxito");
                        ConsultarTrabajadores consultarT = new ConsultarTrabajadores();
                        consultarT.setVisible(true);
                        this.dispose();
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                }

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSolicitudesActionPerformed
        // TODO add your handling code here:
        ConsultarSolicitudes consultarS = new ConsultarSolicitudes();
        consultarS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonSolicitudesActionPerformed

    private void CampoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIDActionPerformed

    private void LabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolverMouseClicked
        // TODO add your handling code here:
        ConsultarTrabajadores consultarT = new ConsultarTrabajadores();
        consultarT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelVolverMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarTrabajador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarTrabajador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarTrabajador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarTrabajador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonActivo;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonEstadisticas;
    private javax.swing.JButton BotonFoto;
    private javax.swing.JRadioButton BotonInactivo;
    private javax.swing.JButton BotonModificarEmpleado;
    private javax.swing.JButton BotonSolicitudes;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JTextField CampoDNI;
    private javax.swing.JTextField CampoDireccion;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoEmpresa;
    private javax.swing.JTextField CampoFechaInicio;
    public static javax.swing.JTextField CampoID;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JCheckBox CheckBoxModificar;
    private javax.swing.JComboBox<String> ComboBoxAgregadoPor;
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelURL;
    private javax.swing.JLabel LabelVolver;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    String urlImagen;
    String estado;
    String tipoEmpleado;

    String dni;
    String nombre;
    String apellidos;
    String telefono;
    String email;

    String direccion;
    String usuario;
    String contrasena;
    Date fechaInicio;
    String agregadoPor;
    String empresa;
    String id;
    int contadorTareas;
    boolean bandera;
    int contadorProyectos;
    boolean banderaP;

}
