/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class PanelGeneral extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdministracion
     */
    public PanelGeneral() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        LabelCirculo.setVisible(false);
        LabelCirculo1.setVisible(false);
        LabelCirculo2.setVisible(false);
        LabelCirculo3.setVisible(false);
        setIconImage(getIconImage());
        Timer timer = new Timer(0, new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                ActualizarHora.actualizarHora(labelhora);

            }
        });
        timer.start();
        
        if (Login.tipoEmpleado.equals("JefeProyecto")) {
            ImagenAdmin.setEnabled(false);
            ImagenEmpleado.setEnabled(false);

        }
        if (Login.tipoEmpleado.equals("Empleado")) {
            ImagenAdmin.setEnabled(false);
            ImagenJefeProyecto.setEnabled(false);
            LabelCirculo.setEnabled(false);
            LabelCirculo1.setEnabled(false);
            LabelAdmin.setEnabled(false);
            LabelJefeProyecto.setEnabled(false);

        }
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ImagenJefeProyecto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ImagenPerfil = new javax.swing.JLabel();
        ImagenEmpleado = new javax.swing.JLabel();
        ImagenAdmin = new javax.swing.JLabel();
        LabelJefeProyecto = new javax.swing.JLabel();
        LabelPerfil = new javax.swing.JLabel();
        LabelEmpleado = new javax.swing.JLabel();
        LabelAdmin = new javax.swing.JLabel();
        LabelCirculo = new javax.swing.JLabel();
        LabelCirculo1 = new javax.swing.JLabel();
        LabelCirculo2 = new javax.swing.JLabel();
        LabelCirculo3 = new javax.swing.JLabel();
        LabelCerrarSesion = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelLogo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setMinimumSize(new java.awt.Dimension(1266, 587));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("¿Qué departamento desea visitar?");
        PanelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        ImagenJefeProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jefeproyecto.png"))); // NOI18N
        ImagenJefeProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenJefeProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenJefeProyectoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenJefeProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenJefeProyectoMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenJefeProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 140, 150));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("x");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 20, 30));

        ImagenPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil_1.png"))); // NOI18N
        ImagenPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenPerfilMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 140, 130));

        ImagenEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empleado_1.png"))); // NOI18N
        ImagenEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenEmpleadoMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 140, 130));

        ImagenAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_2.png"))); // NOI18N
        ImagenAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenAdmin.setFocusable(false);
        ImagenAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenAdminMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, 140));

        LabelJefeProyecto.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        LabelJefeProyecto.setForeground(java.awt.Color.black);
        LabelJefeProyecto.setText("JEFES DE PROYECTO");
        PanelFondo.add(LabelJefeProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 190, -1));

        LabelPerfil.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        LabelPerfil.setForeground(java.awt.Color.black);
        LabelPerfil.setText("VER PERFIL");
        PanelFondo.add(LabelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, 120, -1));

        LabelEmpleado.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        LabelEmpleado.setForeground(java.awt.Color.black);
        LabelEmpleado.setText("EMPLEADOS ");
        PanelFondo.add(LabelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 130, -1));

        LabelAdmin.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        LabelAdmin.setForeground(java.awt.Color.black);
        LabelAdmin.setText("ADMINISTRADORES");
        PanelFondo.add(LabelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 190, -1));

        LabelCirculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        PanelFondo.add(LabelCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 220, 190));

        LabelCirculo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        PanelFondo.add(LabelCirculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 220, 190));

        LabelCirculo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        PanelFondo.add(LabelCirculo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 220, 190));

        LabelCirculo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        PanelFondo.add(LabelCirculo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 220, 190));

        LabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-sesion (1).png"))); // NOI18N
        LabelCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrarSesionMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 70, 70));

        labelhora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelhora.setForeground(java.awt.Color.white);
        PanelFondo.add(labelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 610, 150, 30));

        jLabel5.setBackground(new java.awt.Color(92, 116, 118));
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        jLabel5.setOpaque(true);
        PanelFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, 290, 290));

        jLabel4.setBackground(new java.awt.Color(92, 116, 118));
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        jLabel4.setOpaque(true);
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 290, 290));

        jLabel3.setBackground(new java.awt.Color(92, 116, 118));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        jLabel3.setOpaque(true);
        PanelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 290, 290));

        jLabel2.setBackground(new java.awt.Color(92, 116, 118));
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        jLabel2.setOpaque(true);
        PanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 290, 290));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(87, 186, 144));
        jLabel7.setText("PlanifiKa");
        PanelFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        jLabel6.setBackground(new java.awt.Color(26, 46, 68));
        jLabel6.setOpaque(true);
        PanelFondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarSesionMouseClicked
        // TODO add your handling code here:
        int respuesta = JOptionPane.showOptionDialog(null, "¿Desea cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null, null, null);

        if (respuesta == 0) {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LabelCerrarSesionMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void ImagenPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenPerfilMouseExited
        // TODO add your handling code here:
        LabelCirculo3.setVisible(false);
    }//GEN-LAST:event_ImagenPerfilMouseExited

    private void ImagenPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenPerfilMouseEntered
        // TODO add your handling code here:
        LabelCirculo3.setVisible(true);
    }//GEN-LAST:event_ImagenPerfilMouseEntered

    private void ImagenPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenPerfilMouseClicked
        // TODO add your handling code here:
        Perfil perfil = new Perfil();
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ImagenPerfilMouseClicked

    private void ImagenAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenAdminMouseExited
        // TODO add your handling code here:
        LabelCirculo.setVisible(false);
    }//GEN-LAST:event_ImagenAdminMouseExited

    private void ImagenAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenAdminMouseEntered
        // TODO add your handling code here:
        LabelCirculo.setVisible(true);
    }//GEN-LAST:event_ImagenAdminMouseEntered

    private void ImagenAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenAdminMouseClicked
        // TODO add your handling code here:
        if (Login.tipoEmpleado.equals("Empleado") || Login.tipoEmpleado.equals("JefeProyecto")) {
            JOptionPane.showMessageDialog(null, "No tienes acceso a este departamento");
        } else {
            PanelAdmin panelA = new PanelAdmin();
            panelA.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ImagenAdminMouseClicked

    private void ImagenJefeProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenJefeProyectoMouseExited
        // TODO add your handling code here:
        LabelCirculo1.setVisible(false);
    }//GEN-LAST:event_ImagenJefeProyectoMouseExited

    private void ImagenJefeProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenJefeProyectoMouseEntered
        // TODO add your handling code here:
        LabelCirculo1.setVisible(true);
    }//GEN-LAST:event_ImagenJefeProyectoMouseEntered

    private void ImagenJefeProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenJefeProyectoMouseClicked
        // TODO add your handling code here:
        if (Login.tipoEmpleado.equals("Empleado")) {
            JOptionPane.showMessageDialog(null, "No tienes acceso a este departamento");
        } else {
            PanelJefeProyecto panelJP = new PanelJefeProyecto();
            panelJP.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ImagenJefeProyectoMouseClicked

    private void ImagenEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenEmpleadoMouseExited
        // TODO add your handling code here:
        LabelCirculo2.setVisible(false);
    }//GEN-LAST:event_ImagenEmpleadoMouseExited

    private void ImagenEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenEmpleadoMouseEntered
        // TODO add your handling code here:
        LabelCirculo2.setVisible(true);
    }//GEN-LAST:event_ImagenEmpleadoMouseEntered

    private void ImagenEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenEmpleadoMouseClicked
        // TODO add your handling code here:
        if (Login.tipoEmpleado.equals("JefeProyecto")) {
            JOptionPane.showMessageDialog(null, "No tienes acceso a este departamento");
        }else{
            PanelEmpleado panelE = new PanelEmpleado();
            panelE.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ImagenEmpleadoMouseClicked

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel ImagenAdmin;
    javax.swing.JLabel ImagenEmpleado;
    javax.swing.JLabel ImagenJefeProyecto;
    private javax.swing.JLabel ImagenPerfil;
    private javax.swing.JLabel LabelAdmin;
    private javax.swing.JLabel LabelCerrarSesion;
    private javax.swing.JLabel LabelCirculo;
    private javax.swing.JLabel LabelCirculo1;
    private javax.swing.JLabel LabelCirculo2;
    private javax.swing.JLabel LabelCirculo3;
    private javax.swing.JLabel LabelEmpleado;
    private javax.swing.JLabel LabelJefeProyecto;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelPerfil;
    javax.swing.JPanel PanelFondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel labelhora;
    // End of variables declaration//GEN-END:variables
}
