/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author Hugo
 */
public class PanelAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdministracion
     */
    public PanelAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        LabelCirculo.setVisible(false);
        setIconImage(getIconImage());
        LabelCirculo1.setVisible(false);
        jLabel1.setBackground(new Color(255, 255, 255, 100)); 
        Timer timer = new Timer(0, new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                ActualizarHora.actualizarHora(labelhora);

            }
        });
        timer.start();
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        LabelVolver = new javax.swing.JLabel();
        ImagenGestEmp = new javax.swing.JLabel();
        LabelGestEmp = new javax.swing.JLabel();
        LabelCirculo = new javax.swing.JLabel();
        LabelGestEmp1 = new javax.swing.JLabel();
        ImagenGestEmp1 = new javax.swing.JLabel();
        LabelCirculo1 = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volveratras.png"))); // NOI18N
        LabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolverMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 70, 70));

        ImagenGestEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gestion-del-cambio.png"))); // NOI18N
        ImagenGestEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenGestEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenGestEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenGestEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenGestEmpMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenGestEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 140, 150));

        LabelGestEmp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelGestEmp.setForeground(java.awt.Color.black);
        LabelGestEmp.setText("GESTIONAR TRABAJADOR");
        PanelFondo.add(LabelGestEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 240, -1));

        LabelCirculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        LabelCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCirculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCirculoMouseExited(evt);
            }
        });
        PanelFondo.add(LabelCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 220, 190));

        LabelGestEmp1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelGestEmp1.setForeground(java.awt.Color.black);
        LabelGestEmp1.setText("CREAR TRABAJADOR");
        PanelFondo.add(LabelGestEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, -1));

        ImagenGestEmp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-usuario.png"))); // NOI18N
        ImagenGestEmp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenGestEmp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenGestEmp1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenGestEmp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenGestEmp1MouseExited(evt);
            }
        });
        PanelFondo.add(ImagenGestEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 140, 150));

        LabelCirculo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        LabelCirculo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCirculo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCirculo1MouseExited(evt);
            }
        });
        PanelFondo.add(LabelCirculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 220, 190));

        labelhora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelhora.setForeground(java.awt.Color.white);
        PanelFondo.add(labelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 150, 30));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setOpaque(true);
        PanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 800, 290));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("x");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        jLabel6.setBackground(new java.awt.Color(147, 63, 63));
        jLabel6.setForeground(new java.awt.Color(147, 63, 63));
        jLabel6.setOpaque(true);
        PanelFondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenGestEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenGestEmpMouseClicked
        // TODO add your handling code here:
        ConsultarTrabajadores gestE = new ConsultarTrabajadores();
        gestE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ImagenGestEmpMouseClicked

    private void LabelCirculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculoMouseEntered

    }//GEN-LAST:event_LabelCirculoMouseEntered

    private void LabelCirculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculoMouseExited

    }//GEN-LAST:event_LabelCirculoMouseExited

    private void ImagenGestEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenGestEmpMouseEntered
        // TODO add your handling code here:
        LabelCirculo.setVisible(true);
    }//GEN-LAST:event_ImagenGestEmpMouseEntered

    private void ImagenGestEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenGestEmpMouseExited
        // TODO add your handling code here:
        LabelCirculo.setVisible(false);
    }//GEN-LAST:event_ImagenGestEmpMouseExited

    private void LabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolverMouseClicked
        // TODO add your handling code here:
        PanelGeneral panelG = new PanelGeneral();
        panelG.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelVolverMouseClicked

    private void LabelCirculo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCirculo1MouseEntered

    private void LabelCirculo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCirculo1MouseExited

    private void ImagenGestEmp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenGestEmp1MouseClicked
        // TODO add your handling code here:
        CrearTrabajador crearT = new CrearTrabajador();
        crearT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ImagenGestEmp1MouseClicked

    private void ImagenGestEmp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenGestEmp1MouseEntered
        // TODO add your handling code here:
        LabelCirculo1.setVisible(true);
    }//GEN-LAST:event_ImagenGestEmp1MouseEntered

    private void ImagenGestEmp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenGestEmp1MouseExited
        // TODO add your handling code here:
        LabelCirculo1.setVisible(false);
    }//GEN-LAST:event_ImagenGestEmp1MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenGestEmp;
    private javax.swing.JLabel ImagenGestEmp1;
    private javax.swing.JLabel LabelCirculo;
    private javax.swing.JLabel LabelCirculo1;
    private javax.swing.JLabel LabelGestEmp;
    private javax.swing.JLabel LabelGestEmp1;
    private javax.swing.JLabel LabelVolver;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel labelhora;
    // End of variables declaration//GEN-END:variables
    int hora, minutos, segundos;
}
