/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo
 */
public class PanelEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdministracion
     */
    public PanelEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        LabelCirculo1.setVisible(false);
        LabelCirculo.setVisible(false);
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        LabelGestEmp1 = new javax.swing.JLabel();
        ImagenTareasAsig = new javax.swing.JLabel();
        ImagenSolicitarBaja = new javax.swing.JLabel();
        LabelGestEmp = new javax.swing.JLabel();
        LabelCirculo = new javax.swing.JLabel();
        LabelCirculo1 = new javax.swing.JLabel();
        LabelVolver = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelGestEmp1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelGestEmp1.setForeground(java.awt.Color.white);
        LabelGestEmp1.setText("VER TAREAS ASIGNADAS");
        PanelFondo.add(LabelGestEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 230, -1));

        ImagenTareasAsig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portapapeles.png"))); // NOI18N
        ImagenTareasAsig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenTareasAsig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenTareasAsigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenTareasAsigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenTareasAsigMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenTareasAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, 150));

        ImagenSolicitarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bajo-rendimiento.png"))); // NOI18N
        ImagenSolicitarBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenSolicitarBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenSolicitarBajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenSolicitarBajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenSolicitarBajaMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenSolicitarBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 140, 130));

        LabelGestEmp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelGestEmp.setForeground(java.awt.Color.white);
        LabelGestEmp.setText("SOLICITAR BAJA");
        PanelFondo.add(LabelGestEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 160, -1));

        LabelCirculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        LabelCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCirculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCirculoMouseExited(evt);
            }
        });
        PanelFondo.add(LabelCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 220, 190));

        LabelCirculo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        LabelCirculo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCirculo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCirculo1MouseExited(evt);
            }
        });
        PanelFondo.add(LabelCirculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 220, 190));

        LabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volveratras.png"))); // NOI18N
        LabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolverMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 70, 70));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondotfg.png"))); // NOI18N
        PanelFondo.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenSolicitarBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenSolicitarBajaMouseClicked
        // TODO add your handling code here:
        if (Login.tipoEmpleado.equals("Administrador")) {
            JOptionPane.showMessageDialog(null, "Tu departamento no puede solicitar baja");
        } else {
            /*SolicitarBaja solicitarB = new SolicitarBaja();
            solicitarB.setVisible(true);
            this.dispose();
             */
        }
    }//GEN-LAST:event_ImagenSolicitarBajaMouseClicked

    private void LabelCirculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculoMouseEntered

    }//GEN-LAST:event_LabelCirculoMouseEntered

    private void LabelCirculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculoMouseExited

    }//GEN-LAST:event_LabelCirculoMouseExited

    private void LabelCirculo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCirculo1MouseEntered

    private void LabelCirculo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCirculo1MouseExited

    private void ImagenTareasAsigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenTareasAsigMouseEntered
        // TODO add your handling code here:
        LabelCirculo1.setVisible(true);
    }//GEN-LAST:event_ImagenTareasAsigMouseEntered

    private void ImagenTareasAsigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenTareasAsigMouseExited
        // TODO add your handling code here:
        LabelCirculo1.setVisible(false);
    }//GEN-LAST:event_ImagenTareasAsigMouseExited

    private void ImagenSolicitarBajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenSolicitarBajaMouseEntered
        // TODO add your handling code here:
        LabelCirculo.setVisible(true);
    }//GEN-LAST:event_ImagenSolicitarBajaMouseEntered

    private void ImagenSolicitarBajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenSolicitarBajaMouseExited
        // TODO add your handling code here:
        LabelCirculo.setVisible(false);
    }//GEN-LAST:event_ImagenSolicitarBajaMouseExited

    private void LabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolverMouseClicked
        // TODO add your handling code here:
        PanelGeneral panelG = new PanelGeneral();
        panelG.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelVolverMouseClicked

    private void ImagenTareasAsigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenTareasAsigMouseClicked
        // TODO add your handling code here:
        if (Login.tipoEmpleado.equals("Administrador")) {
            JOptionPane.showMessageDialog(null, "Tu departamento no tareas asignadas");
        } else {
            TareasAsignadas tareasA = new TareasAsignadas();
            tareasA.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ImagenTareasAsigMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenSolicitarBaja;
    private javax.swing.JLabel ImagenTareasAsig;
    private javax.swing.JLabel LabelCirculo;
    private javax.swing.JLabel LabelCirculo1;
    private javax.swing.JLabel LabelGestEmp;
    private javax.swing.JLabel LabelGestEmp1;
    private javax.swing.JLabel LabelVolver;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables
}
