/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class PanelEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdministracion
     */
    public PanelEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        LabelCirculo1.setVisible(false);
        LabelCirculo.setVisible(false);
        setIconImage(getIconImage());
        Timer timer = new Timer(0, new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                ActualizarHora.actualizarHora(labelhora);

            }
        });
        timer.start();
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        LabelGestEmp1 = new javax.swing.JLabel();
        ImagenTareasAsig = new javax.swing.JLabel();
        ImagenSolicitudes = new javax.swing.JLabel();
        LabelGestEmp = new javax.swing.JLabel();
        LabelCirculo = new javax.swing.JLabel();
        LabelCirculo1 = new javax.swing.JLabel();
        LabelVolver = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelLogo3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelGestEmp1.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        LabelGestEmp1.setForeground(java.awt.Color.black);
        LabelGestEmp1.setText("VER TAREAS ASIGNADAS");
        PanelFondo.add(LabelGestEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 240, -1));

        ImagenTareasAsig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lista-de-tareas.png"))); // NOI18N
        ImagenTareasAsig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenTareasAsig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenTareasAsigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenTareasAsigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenTareasAsigMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenTareasAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 130, 150));

        ImagenSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/conversacion.png"))); // NOI18N
        ImagenSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenSolicitudesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenSolicitudesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenSolicitudesMouseExited(evt);
            }
        });
        PanelFondo.add(ImagenSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 140, 130));

        LabelGestEmp.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        LabelGestEmp.setForeground(java.awt.Color.black);
        LabelGestEmp.setText("SOLICITUDES");
        PanelFondo.add(LabelGestEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 130, -1));

        LabelCirculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        LabelCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCirculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCirculoMouseExited(evt);
            }
        });
        PanelFondo.add(LabelCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 220, 190));

        LabelCirculo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCirculo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circuloback.png"))); // NOI18N
        LabelCirculo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelCirculo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelCirculo1MouseExited(evt);
            }
        });
        PanelFondo.add(LabelCirculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 220, 190));

        LabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-hacia-atras.png"))); // NOI18N
        LabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolverMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 70, 70));

        labelhora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelhora.setForeground(java.awt.Color.white);
        PanelFondo.add(labelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 150, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("x");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 30));

        jLabel3.setBackground(new java.awt.Color(92, 116, 118));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        jLabel3.setOpaque(true);
        PanelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 300, 290));

        jLabel2.setBackground(new java.awt.Color(92, 116, 118));
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        jLabel2.setOpaque(true);
        PanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 290, 290));

        LabelLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogo3MouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 186, 144));
        jLabel4.setText("PlanifiKa");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        jLabel6.setBackground(new java.awt.Color(26, 46, 68));
        jLabel6.setOpaque(true);
        PanelFondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenSolicitudesMouseClicked
        // TODO add your handling code here:
        if (Login.tipoEmpleado.equals("Administrador")) {
            JOptionPane.showMessageDialog(null, "Tu departamento debe ver las solicitudes desde el panel de gestión de trabajadores");
        } else {
            bandera = false;
            ConsultarSolicitudes consultarS = new ConsultarSolicitudes();
            consultarS.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ImagenSolicitudesMouseClicked

    private void LabelCirculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculoMouseEntered

    }//GEN-LAST:event_LabelCirculoMouseEntered

    private void LabelCirculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculoMouseExited

    }//GEN-LAST:event_LabelCirculoMouseExited

    private void LabelCirculo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCirculo1MouseEntered

    private void LabelCirculo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCirculo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelCirculo1MouseExited

    private void ImagenTareasAsigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenTareasAsigMouseEntered
        // TODO add your handling code here:
        LabelCirculo1.setVisible(true);
    }//GEN-LAST:event_ImagenTareasAsigMouseEntered

    private void ImagenTareasAsigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenTareasAsigMouseExited
        // TODO add your handling code here:
        LabelCirculo1.setVisible(false);
    }//GEN-LAST:event_ImagenTareasAsigMouseExited

    private void ImagenSolicitudesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenSolicitudesMouseEntered
        // TODO add your handling code here:
        LabelCirculo.setVisible(true);
    }//GEN-LAST:event_ImagenSolicitudesMouseEntered

    private void ImagenSolicitudesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenSolicitudesMouseExited
        // TODO add your handling code here:
        LabelCirculo.setVisible(false);
    }//GEN-LAST:event_ImagenSolicitudesMouseExited

    private void LabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolverMouseClicked
        // TODO add your handling code here:
        PanelGeneral panelG = new PanelGeneral();
        panelG.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelVolverMouseClicked

    private void ImagenTareasAsigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenTareasAsigMouseClicked
        // TODO add your handling code here:
        if (Login.tipoEmpleado.equals("Administrador")) {
            JOptionPane.showMessageDialog(null, "Tu departamento no tareas asignadas");
        } else {
            TareasAsignadas tareasA = new TareasAsignadas();
            tareasA.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ImagenTareasAsigMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void LabelLogo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogo3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogo3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenSolicitudes;
    private javax.swing.JLabel ImagenTareasAsig;
    private javax.swing.JLabel LabelCirculo;
    private javax.swing.JLabel LabelCirculo1;
    private javax.swing.JLabel LabelGestEmp;
    private javax.swing.JLabel LabelGestEmp1;
    private javax.swing.JLabel LabelLogo3;
    private javax.swing.JLabel LabelVolver;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel labelhora;
    // End of variables declaration//GEN-END:variables
    static boolean bandera = true;
}
