/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG;

import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage()); 
        Timer timer = new Timer(0, new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                ActualizarHora.actualizarHora(labelhora);

            }
        });
        timer.start();

        Connection cn = conexion.Conexion.conectar();
        try {

            PreparedStatement ps = cn.prepareStatement("SELECT * FROM usuarios WHERE ID = ?");
            ps.setInt(1, Login.idInicioSesion);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                id = rs.getString(1);
                dni = rs.getString(2);
                nombre = rs.getString(3);
                apellidos = rs.getString(4);
                telefono = rs.getString(5);
                email = rs.getString(6);
                empresa = rs.getString(7);
                direccion = rs.getString(8);
                usuario = rs.getString(9);
                contrasena = rs.getString(10);
                estado = rs.getString(11);
                tipoEmpleado = rs.getString(12);
                fechaInicio = rs.getDate(13);
                agregadoPor = rs.getString(14);
                urlImagen = rs.getString(15);
            }

            rs.close();
            rs.close();
            
            CampoDNI.setText(dni);
            CampoNombreCompleto.setText(nombre + " " + apellidos);
            CampoTelefono.setText(telefono);
            CampoEmail.setText(email);
            CampoDireccion.setText(direccion);
            CampoFechaInicio.setText(fechaInicio.toString());
            CampoAgregadoPor.setText(agregadoPor);
            CampoEmpresa.setText(empresa);
            CampoEstado.setText(estado);
            CampoTipo.setText(tipoEmpleado);

            ImageIcon icono = new ImageIcon("C:\\Users\\Hugo\\OneDrive\\Documentos\\NetBeansProjects\\TFG\\src\\images\\" + urlImagen);
            int anchoLabel = LabelImagen.getWidth();
            int altoLabel = LabelImagen.getHeight();
            Image imagenRedimensionada = icono.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);

            LabelImagen.setIcon(iconoRedimensionado);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        PanelFoto = new javax.swing.JPanel();
        LabelImagen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CampoAgregadoPor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CampoDireccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CampoTelefono = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        CampoDNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CampoNombreCompleto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CampoEmpresa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CampoTipo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CampoEstado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        labelhora = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CampoFechaInicio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        LabelCerrarSesion = new javax.swing.JLabel();
        LabelLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout PanelFotoLayout = new javax.swing.GroupLayout(PanelFoto);
        PanelFoto.setLayout(PanelFotoLayout);
        PanelFotoLayout.setHorizontalGroup(
            PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        PanelFotoLayout.setVerticalGroup(
            PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFotoLayout.createSequentialGroup()
                .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        PanelFondo.add(PanelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 430, 440));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Teléfono:");
        PanelFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, -1));

        CampoAgregadoPor.setBackground(new java.awt.Color(92, 116, 118));
        CampoAgregadoPor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoAgregadoPor.setForeground(java.awt.Color.white);
        CampoAgregadoPor.setDisabledTextColor(java.awt.Color.white);
        CampoAgregadoPor.setEnabled(false);
        CampoAgregadoPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAgregadoPorActionPerformed(evt);
            }
        });
        PanelFondo.add(CampoAgregadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 330, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Agregado por:");
        PanelFondo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        CampoDireccion.setBackground(new java.awt.Color(92, 116, 118));
        CampoDireccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoDireccion.setForeground(java.awt.Color.white);
        CampoDireccion.setDisabledTextColor(java.awt.Color.white);
        CampoDireccion.setEnabled(false);
        PanelFondo.add(CampoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 330, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Direccion:");
        PanelFondo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Correo electrónico:");
        PanelFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        CampoTelefono.setBackground(new java.awt.Color(92, 116, 118));
        CampoTelefono.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoTelefono.setForeground(java.awt.Color.white);
        CampoTelefono.setDisabledTextColor(java.awt.Color.white);
        CampoTelefono.setEnabled(false);
        PanelFondo.add(CampoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 330, -1));

        CampoEmail.setBackground(new java.awt.Color(92, 116, 118));
        CampoEmail.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoEmail.setForeground(java.awt.Color.white);
        CampoEmail.setDisabledTextColor(java.awt.Color.white);
        CampoEmail.setEnabled(false);
        PanelFondo.add(CampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 330, -1));

        CampoDNI.setBackground(new java.awt.Color(92, 116, 118));
        CampoDNI.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoDNI.setForeground(java.awt.Color.white);
        CampoDNI.setDisabledTextColor(java.awt.Color.white);
        CampoDNI.setEnabled(false);
        CampoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDNIActionPerformed(evt);
            }
        });
        PanelFondo.add(CampoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 210, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("DNI:");
        PanelFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, -1, -1));

        CampoNombreCompleto.setBackground(new java.awt.Color(92, 116, 118));
        CampoNombreCompleto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoNombreCompleto.setForeground(java.awt.Color.white);
        CampoNombreCompleto.setDisabledTextColor(java.awt.Color.white);
        CampoNombreCompleto.setEnabled(false);
        PanelFondo.add(CampoNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 330, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Nombre completo:");
        PanelFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        CampoEmpresa.setBackground(new java.awt.Color(92, 116, 118));
        CampoEmpresa.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoEmpresa.setForeground(java.awt.Color.white);
        CampoEmpresa.setDisabledTextColor(java.awt.Color.white);
        CampoEmpresa.setEnabled(false);
        PanelFondo.add(CampoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 210, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Empresa:");
        PanelFondo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 550, -1, -1));

        CampoTipo.setBackground(new java.awt.Color(92, 116, 118));
        CampoTipo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoTipo.setForeground(java.awt.Color.white);
        CampoTipo.setDisabledTextColor(java.awt.Color.white);
        CampoTipo.setEnabled(false);
        PanelFondo.add(CampoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 210, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Tipo:");
        PanelFondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, -1, -1));

        CampoEstado.setBackground(new java.awt.Color(92, 116, 118));
        CampoEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoEstado.setForeground(java.awt.Color.white);
        CampoEstado.setDisabledTextColor(java.awt.Color.white);
        CampoEstado.setEnabled(false);
        CampoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEstadoActionPerformed(evt);
            }
        });
        PanelFondo.add(CampoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 210, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Estado:");
        PanelFondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, -1, -1));

        labelhora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelhora.setForeground(java.awt.Color.white);
        PanelFondo.add(labelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 150, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("x");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        PanelFondo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 20, 30));

        CampoFechaInicio.setBackground(new java.awt.Color(92, 116, 118));
        CampoFechaInicio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        CampoFechaInicio.setForeground(java.awt.Color.white);
        CampoFechaInicio.setDisabledTextColor(java.awt.Color.white);
        CampoFechaInicio.setEnabled(false);
        PanelFondo.add(CampoFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 210, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Fecha de inicio:");
        PanelFondo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, -1, -1));

        LabelCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-hacia-atras.png"))); // NOI18N
        LabelCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrarSesionMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 70, 70));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcono.png"))); // NOI18N
        LabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogoMouseClicked(evt);
            }
        });
        PanelFondo.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 186, 144));
        jLabel4.setText("PlanifiKa");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        jLabel6.setBackground(new java.awt.Color(26, 46, 68));
        jLabel6.setOpaque(true);
        PanelFondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDNIActionPerformed

    private void CampoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEstadoActionPerformed

    private void LabelCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarSesionMouseClicked
        // TODO add your handling code here:
        PanelGeneral panelG = new PanelGeneral();
        panelG.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelCerrarSesionMouseClicked

    private void CampoAgregadoPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAgregadoPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoAgregadoPorActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void LabelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogoMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LabelLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoAgregadoPor;
    private javax.swing.JTextField CampoDNI;
    private javax.swing.JTextField CampoDireccion;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoEmpresa;
    private javax.swing.JTextField CampoEstado;
    private javax.swing.JTextField CampoFechaInicio;
    private javax.swing.JTextField CampoNombreCompleto;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JTextField CampoTipo;
    private javax.swing.JLabel LabelCerrarSesion;
    private javax.swing.JLabel LabelImagen;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelFoto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel labelhora;
    // End of variables declaration//GEN-END:variables
      String urlImagen;
    String estado;
    String tipoEmpleado;

    String dni;
    String nombre;
    String apellidos;
    String telefono;
    String email;

    String direccion;
    String usuario;
    String contrasena;
    Date fechaInicio;
    String agregadoPor;
    String empresa;
    String id;

}
