/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoTFG.ejecucion;

import codigoTFG.Login;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class BarraProgreso extends JFrame implements Runnable {

    private boolean bandera;

    /**
     * Creates new form NewJFrame
     */
    public BarraProgreso() {
        initComponents();
        setTitle("PlanifiKa");
        setLocationRelativeTo(null);
        setResizable(false);
        bandera = false;
        
        setIconImage(getIconImage());
        Thread hilo = new Thread(this);
        hilo.start();
        
 
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logoIcono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jbar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbar.setBackground(java.awt.Color.lightGray);
        jbar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbar.setForeground(new java.awt.Color(26, 46, 68));
        jbar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbar.setStringPainted(true);
        PanelFondo.add(jbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 580, 60));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        jLabel4.setForeground(java.awt.Color.lightGray);
        jLabel4.setText("Iniciando programa...");
        PanelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PlanifiKa.png"))); // NOI18N
        PanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1230, 660));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {

        for (int i = 1; i <= 100; i++) {
            try {
                Thread.sleep(30);
                this.getBar().setValue(i);

                if (this.getBar().getValue() == 100) {
                    this.bandera = true;

                }
            } catch (InterruptedException ex) {
                Thread.currentThread().isInterrupted();
            }

        }
        if (bandera) {
            this.dispose();
            bandera = false;
            Login login = new Login();
            login.setVisible(true);
        }
    }

    public void setBar(JProgressBar bar) {
        this.jbar = bar;
    }

    public JProgressBar getBar() {
        return jbar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jbar;
    // End of variables declaration//GEN-END:variables
}
